version: '3.8'

services:
  db:
    image: postgres:14.11
    container_name: postgresdb
    environment:
      POSTGRES_DB: cobaia
      POSTGRES_USER: cobaia_user
      POSTGRES_PASSWORD: cobaia_password
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

volumes:
  postgres-data:
